name: DiffDRR
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pytorch>=1.13
  - torchvision
  - pytorch-cuda=11.7
  - libcufile>=1.4,<1.5
  - pydicom
  - matplotlib
  - seaborn
  - black
  - flake8
  - ipykernel
  - ipywidgets
  - tqdm
  - pytest
  - imageio
  - pip:
      - -e .  # Install the local package (DiffDRR)
